// Generated by gencpp from file rover_control/Serialmsg.msg
// DO NOT EDIT!


#ifndef ROVER_CONTROL_MESSAGE_SERIALMSG_H
#define ROVER_CONTROL_MESSAGE_SERIALMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rover_control
{
template <class ContainerAllocator>
struct Serialmsg_
{
  typedef Serialmsg_<ContainerAllocator> Type;

  Serialmsg_()
    : motor()
    , robotarm()
    , battery()
    , lora()
    , sensor()  {
    }
  Serialmsg_(const ContainerAllocator& _alloc)
    : motor(_alloc)
    , robotarm(_alloc)
    , battery(_alloc)
    , lora(_alloc)
    , sensor(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _motor_type;
  _motor_type motor;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _robotarm_type;
  _robotarm_type robotarm;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _battery_type;
  _battery_type battery;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _lora_type;
  _lora_type lora;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _sensor_type;
  _sensor_type sensor;




  typedef boost::shared_ptr< ::rover_control::Serialmsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rover_control::Serialmsg_<ContainerAllocator> const> ConstPtr;

}; // struct Serialmsg_

typedef ::rover_control::Serialmsg_<std::allocator<void> > Serialmsg;

typedef boost::shared_ptr< ::rover_control::Serialmsg > SerialmsgPtr;
typedef boost::shared_ptr< ::rover_control::Serialmsg const> SerialmsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rover_control::Serialmsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rover_control::Serialmsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rover_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'rover_control': ['/home/hgaren/catkin_ws1/src/rover_control/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rover_control::Serialmsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rover_control::Serialmsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_control::Serialmsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_control::Serialmsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_control::Serialmsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_control::Serialmsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rover_control::Serialmsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f7d62d3f0b4e8ce27ed379c441273f9e";
  }

  static const char* value(const ::rover_control::Serialmsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf7d62d3f0b4e8ce2ULL;
  static const uint64_t static_value2 = 0x7ed379c441273f9eULL;
};

template<class ContainerAllocator>
struct DataType< ::rover_control::Serialmsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rover_control/Serialmsg";
  }

  static const char* value(const ::rover_control::Serialmsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rover_control::Serialmsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
   string motor\n\
   string robotarm\n\
   string battery\n\
   string lora\n\
   string sensor\n\
   \n\
\n\
";
  }

  static const char* value(const ::rover_control::Serialmsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rover_control::Serialmsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motor);
      stream.next(m.robotarm);
      stream.next(m.battery);
      stream.next(m.lora);
      stream.next(m.sensor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Serialmsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rover_control::Serialmsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rover_control::Serialmsg_<ContainerAllocator>& v)
  {
    s << indent << "motor: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.motor);
    s << indent << "robotarm: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.robotarm);
    s << indent << "battery: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.battery);
    s << indent << "lora: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.lora);
    s << indent << "sensor: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.sensor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROVER_CONTROL_MESSAGE_SERIALMSG_H
